import { Inter } from 'next/font/google'
import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { ChangeEvent, FormEvent, useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({
  variable: '--inter-font',
  subsets: ['latin']
})

export default function Home() {
  const [word, setWord] = useState('')
  const router = useRouter()

  function handleOnSubmitForm(e: FormEvent){
    e.preventDefault()

    router.push(`words/${word}`)
  }

  function handleOnChangeInput(e: ChangeEvent<HTMLInputElement>) {
    setWord(e.target.value)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className={styles.main}>
          <h1>Dicionario</h1>
          <form onSubmit={handleOnSubmitForm}>
            <input onChange={handleOnChangeInput} type="text" placeholder='Pesquise aqui'/>
          </form>

          <div>
            <strong>Recentes</strong>
            <ul>
              <li>Django</li>
              <li>generalista</li>
              <li>Teste</li>
            </ul>
          </div>
        </div>
      </main>
    </>
  )
}
